---
apiVersion: v1
data:
    privateKey: ENC[AES256_GCM,data:s7MY83uDoe5DaademcfatTkvTcQNChpHjZM7RMBLycYpqwlgkZFyWe60+qdr6fwI2geC1oZ7hcZpL9ZFai0ZlrqKkbSkLIptWiNH08gHmAH6Jv3bcJWCrgoVa8kB0k91oZ4BIvWIqRN9LUwjo5wNuB/YA0a+uIw4dykLnOVsGGpbfzkIO+f6zmk2RsnkWbDRWFHFs/+S2rfqIoHExFm4UlK+AJ+9UAxesWXYt7SavFAw0IEFSyE2i7ftYVSg+kUUSv1J4W7D5OjGREnzj4TLxmZlq4zuR7KGGaHROZKynFvvZudnzBWyh+5fwqqq9oWaT8w2aAk4UgFje2pBgH9pT9xhd9iBZT1Rb/Lu//4guiwLdo7ROTppvwTmyFUd4iwn6bqDNBCDpeMBmR7WdmTIfiPuzaDDKnVzEN1dO1k3aM99AW5xkGRe10bPPJMb55z2c3lCu7diUhuFlQUBKXfPO4p5ZN4bdOEVxAmgMqaioU95JTUROKBn9dQsUtVKML1pED1dQoDG15JJm1Av5kiCah496EyK91nLz5jSWa0efOnb3kxCuApybCWUvyCibkWGKZ9quEu67mFmZlX6NHcV807oldPwCd0wWgBrkAxlq9Ceyg0dz05+Se3CMQqrGJi2mcbassLL/8xz6y2i00wCc8+a+gGICF70zSq3Wq9I8efy74Kdfk+TykGF3u5oFM56K5x8rKARnIpdV2VCwiIsakCN2IQCdNuT2Pkm9WcCxZYVOdDxa0PTkf9SInrc286ipHzXWW+pIVxgNj2SoCMy0rWYIJceR/RwuG4l8nHvRoOp2NA1moS0t/HDo0mQyBZxEQGwmWZ+Clvo3oQbU9O+tss5af4aCR2KF9E3dir+lrzMQV643Xp1XgjVQ1Nrd/4bRq2ogwEwVbm5I2TLRP8=,iv:MJdUwdGefy0zmxx8rSBBtby4DZLvoeDFnevYeCbHqhw=,tag:0lzsevx8Q/zryeho3VwnRw==,type:str]
    username: ENC[AES256_GCM,data:ok+sfw==,iv:zSLIRv6RxEEVZFHc3ogTUnPDMEMIGM7PoBrweQHtUEU=,tag:Wcrd+AM8crT95hWODXQEKQ==,type:str]
kind: Secret
metadata:
    annotations:
        jenkins.io/credentials-description: jenkins-easy repository SSH key
    labels:
        jenkins.io/credentials-type: basicSSHUserPrivateKey
    name: jenkins-easy
    namespace: jenkins
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-06-26T10:12:28Z"
    mac: ENC[AES256_GCM,data:dwKe59knx3PChTXhP5vRvV/gPb10kb3ky1HzuHgnn51b9lVyYOEqnEnQKZTAxUA+2jAckAGkPkjBd92U3FQRZxFPkq6XcK/ROK4roi93xiRPulukHY/u3qgXEuohHkU8Nng6/4V/hb4U3ww3BG2y+jruaUdMiTYU15s+7QDYUbU=,iv:DiODyTAVkEMg/zZEIcx82HCrBpQisIZhvLm4DtQedi8=,tag:Y+Faf+BR20DEguO4VG67ew==,type:str]
    pgp:
        - created_at: "2021-06-26T10:12:28Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0aRb+h7MJSBAQ//eXxw18xG8zjZwP+5I0iRlrQjsrjfBMEwGt59ONbMjpBR
            3m+LokhqpU5rw2u8nyME5vxBM0KufeJKW5tkfunJLmb9j4OoVN/RD4EUAFTXbKkM
            MJFl5YFORmnh7tpYqtwb1zY8mYwzk/IX+TGHrrNJJfP2JIjA8O6omnVzegDH2PpK
            R1rHRoZFqkUDd/hFAsDEtt0ZNnpQiZ1W1xHTrnu1EnKevoNe+dv2CdzRirbF7sbt
            uTDeiWZ2fTfOCGbmfRtko6vPM1KxrJxlwtgu/+pZCJd02JgVWCsSUDalVHjQFxI9
            jTLQr+XoRzOfuaCg8pww1wi8RbM49wjnc2sq7M/4Z2seUGy//jARkgfYo1uNmTzg
            3A1IHz6BRR4ILqdm05zjrSFWCfxV+gmTAOreOo1Px3tSIDyTBGuU7zgURSJm26ix
            24Wk4TkLu6JS8NQs9K13VWenIyr5IYdeb3IsckfdHQJ7db1xHiXXBO8G4mWo/VL9
            woEa8AzcD274k3MqWmd1Q2WyPzY5io3lQXg7LwuYjYkbbXMskeUMbd2vJXH2ki2F
            kM8L9S7DeA0wToD1bmoZlwX73khdHuuDWPlrNwnD/F/xZO7Fg/UpsMW+lnt7LAfq
            A790AVWB5Fqt2ChzzX9iAiMYvEQFntQPyfYv6UOj6n6KKyaAHAUzCYENtrUdQKnS
            XgGuXFd8eQdG1UgqGVP5S4+wXI70hOq9Vy5YAfb47oQgyQzwck3gW9aw+c+rou9b
            h4a6vI5DJq4YmRXrrSqVImsvhNqp6oIGSKtZkQBp2bbOVVw6aE2pFK/eApg91u4=
            =ySxm
            -----END PGP MESSAGE-----
          fp: 181C3AA8E16A40DF73F037F21B2B5982CB595209
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
apiVersion: v1
kind: Secret
metadata:
    name: oidc-config
    namespace: jenkins
stringData:
    okta-client-id: ENC[AES256_GCM,data:XhLWikuYif8WqduLIZOZivbn7jo=,iv:Ti2H0OnLHTduqi0G2Vpx/0l+0VAPve7Dw+9CK8BFD74=,tag:VKEhUWmy7ziM5MGe9zN8gQ==,type:str]
    okta-client-secret: ENC[AES256_GCM,data:ENQCA61HaUa8HS2mlAoTsix+3Pj8Ru9Jhu5oimPGE9RuqkYj9IW/HA==,iv:p1IwNu1qis6NA6/06s37PE1MHZVNetqcGN5ra5PLWmw=,tag:6xZiTf3urefISWtsOFTb5Q==,type:str]
    okta-org-name: ENC[AES256_GCM,data:WsdRsRoXyAlncbU=,iv:xDA+8S3IkTN2WUck09otQpyfkvRiE7BjfMQG7K3aOuc=,tag:8Bs4tinVTE/0zb36A8c9vg==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-06-26T10:12:28Z"
    mac: ENC[AES256_GCM,data:dwKe59knx3PChTXhP5vRvV/gPb10kb3ky1HzuHgnn51b9lVyYOEqnEnQKZTAxUA+2jAckAGkPkjBd92U3FQRZxFPkq6XcK/ROK4roi93xiRPulukHY/u3qgXEuohHkU8Nng6/4V/hb4U3ww3BG2y+jruaUdMiTYU15s+7QDYUbU=,iv:DiODyTAVkEMg/zZEIcx82HCrBpQisIZhvLm4DtQedi8=,tag:Y+Faf+BR20DEguO4VG67ew==,type:str]
    pgp:
        - created_at: "2021-06-26T10:12:28Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0aRb+h7MJSBAQ//eXxw18xG8zjZwP+5I0iRlrQjsrjfBMEwGt59ONbMjpBR
            3m+LokhqpU5rw2u8nyME5vxBM0KufeJKW5tkfunJLmb9j4OoVN/RD4EUAFTXbKkM
            MJFl5YFORmnh7tpYqtwb1zY8mYwzk/IX+TGHrrNJJfP2JIjA8O6omnVzegDH2PpK
            R1rHRoZFqkUDd/hFAsDEtt0ZNnpQiZ1W1xHTrnu1EnKevoNe+dv2CdzRirbF7sbt
            uTDeiWZ2fTfOCGbmfRtko6vPM1KxrJxlwtgu/+pZCJd02JgVWCsSUDalVHjQFxI9
            jTLQr+XoRzOfuaCg8pww1wi8RbM49wjnc2sq7M/4Z2seUGy//jARkgfYo1uNmTzg
            3A1IHz6BRR4ILqdm05zjrSFWCfxV+gmTAOreOo1Px3tSIDyTBGuU7zgURSJm26ix
            24Wk4TkLu6JS8NQs9K13VWenIyr5IYdeb3IsckfdHQJ7db1xHiXXBO8G4mWo/VL9
            woEa8AzcD274k3MqWmd1Q2WyPzY5io3lQXg7LwuYjYkbbXMskeUMbd2vJXH2ki2F
            kM8L9S7DeA0wToD1bmoZlwX73khdHuuDWPlrNwnD/F/xZO7Fg/UpsMW+lnt7LAfq
            A790AVWB5Fqt2ChzzX9iAiMYvEQFntQPyfYv6UOj6n6KKyaAHAUzCYENtrUdQKnS
            XgGuXFd8eQdG1UgqGVP5S4+wXI70hOq9Vy5YAfb47oQgyQzwck3gW9aw+c+rou9b
            h4a6vI5DJq4YmRXrrSqVImsvhNqp6oIGSKtZkQBp2bbOVVw6aE2pFK/eApg91u4=
            =ySxm
            -----END PGP MESSAGE-----
          fp: 181C3AA8E16A40DF73F037F21B2B5982CB595209
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
